django_logbox/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_logbox/admin.py,sha256=QptmQVIdWQKmuhsCeWgd5-M0OQlfkeeMgdeA3e8yzWo,2080
django_logbox/app_settings.py,sha256=h-FS4GShz2-tiDQBe_89vQX254EYauBgCpxejmo--N4,1712
django_logbox/apps.py,sha256=5CaHPyN3Zoa35CN9TkaidibGUXcYd0ge3rA1AocA2gw,243
django_logbox/locale/ko_KR/LC_MESSAGES/django.mo,sha256=jBgRriBGmvMappVjw0wu2McHhDtD9uDWiQdskcWl2qs,2954
django_logbox/locale/ko_KR/LC_MESSAGES/django.po,sha256=hwXMKIEOZfPk_zHAr6JKp3EbL9UrCmZJSuCkU37bDR4,4058
django_logbox/middlewares.py,sha256=ehn4bTC45olTGD8GTyJ9WUKGFFT5K-xJWrtRUsT9mVM,2348
django_logbox/migrations/0001_initial.py,sha256=6VT2pvAYWeTYYkxWm9XFi30U8cE-xJGADTvwQucEgqg,1999
django_logbox/migrations/0002_remove_serverlog_duration.py,sha256=1Xz2hUND59e31opN7LqflRS8Jm3JFZOKP4VJvxBEWnE,327
django_logbox/migrations/0003_rename_exception_serverlog_exception_type_and_more.py,sha256=LHYtGqdFWGwdgXMMKYJKtwcfMe23DI8pkAkK3_lc7JM,592
django_logbox/migrations/0004_alter_serverlog_client_ip_and_more.py,sha256=YmJjhVqFmQHBAQaKtJTH3ysIe7LjXRJ-oMNnfvIFpck,4123
django_logbox/migrations/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
django_logbox/models.py,sha256=CDkc2cG97cMRFcX6lNdzs_RLafz1-sh9U5IdcoEXIrA,2555
django_logbox/threading.py,sha256=z_gJSNEN1MgwHIr6bUCEb32Qimqu8a5yE7AuvKWsGXQ,1607
django_logbox/utils.py,sha256=5kmvN0Lcvq6la2hG8BxmG3-O4QydOn9aiXqYpk4O9u0,3056
django_logbox-0.0.8.dist-info/METADATA,sha256=e3D-y4T1FQA_u7sZh8J4hyITPWO3YB1wveKBhgb5Oi4,2997
django_logbox-0.0.8.dist-info/WHEEL,sha256=Nq82e9rUAnEjt98J6MlVmMCZb-t9cYE2Ir1kpBmnWfs,88
django_logbox-0.0.8.dist-info/RECORD,,
